Repository ros-planning/navigation, pull requests merged in 2019-06, with the labels that each got.

#751 Fix for #750: Added publishZeroVelocity() before starting planner
  move_base/src/move_base.cpp
Labels: melodic, move_base

#833 [kinetic] Provide different negative values for unknown and out-of-map costs on footprintCost
  base_local_planner/include/base_local_planner/costmap_model.h
  base_local_planner/include/base_local_planner/world_model.h
  base_local_planner/src/costmap_model.cpp
Labels: kinetic, planners

#838 [melodic] Add parameters to tailor clear costmaps recovery behavior
  clear_costmap_recovery/include/clear_costmap_recovery/clear_costmap_recovery.h
  clear_costmap_recovery/src/clear_costmap_recovery.cpp
Labels: melodic, move_base

#738 Costmap_2d plugin universal parameters and pre-hydro warnings
  costmap_2d/cfg/Costmap2D.cfg
  costmap_2d/include/costmap_2d/costmap_2d_ros.h
  costmap_2d/src/costmap_2d_ros.cpp
Labels: costmap_2d, melodic

#862 ROS_DEBUG prints incorrect gen_id & incorrect namespace for /latch_xy_goal_tolerance
  base_local_planner/include/base_local_planner/latched_stop_rotate_controller.h
  base_local_planner/src/latched_stop_rotate_controller.cpp
  base_local_planner/src/simple_scored_sampling_planner.cpp
  dwa_local_planner/src/dwa_planner_ros.cpp
Labels: kinetic, planners
